'use client';

import { useState, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { DataTable } from '@/components/ui/data-table';
import { SearchInput } from '@/components/ui/search-input';
import { MultiFilter } from '@/components/ui/multi-filter';
import { 
  Bell, 
  AlertTriangle, 
  CheckCircle, 
  Clock, 
  DollarSign,
  Users,
  TrendingDown,
  Settings,
  Send,
  Eye,
  Trash2,
  Plus,
  MessageSquare,
  Mail,
  Smartphone
} from 'lucide-react';

interface Alert {
  id: string;
  type: 'FEE_OVERDUE' | 'LOW_CASH_FLOW' | 'BUDGET_EXCEEDED' | 'PAYMENT_FAILED' | 'COLLECTION_TARGET' | 'SYSTEM';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  title: string;
  message: string;
  details?: string;
  studentId?: string;
  studentName?: string;
  amount?: number;
  dueDate?: string;
  categoryId?: string;
  categoryName?: string;
  threshold?: number;
  currentValue?: number;
  status: 'ACTIVE' | 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED';
  createdAt: string;
  acknowledgedAt?: string;
  acknowledgedBy?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  actionRequired: boolean;
  autoGenerated: boolean;
}

interface NotificationRule {
  id: string;
  name: string;
  description: string;
  triggerType: 'FEE_OVERDUE' | 'PAYMENT_RECEIVED' | 'BUDGET_THRESHOLD' | 'COLLECTION_TARGET' | 'CASH_FLOW';
  conditions: Array<{
    field: string;
    operator: string;
    value: any;
  }>;
  recipients: Array<{
    type: 'ROLE' | 'USER' | 'EMAIL';
    value: string;
  }>;
  channels: Array<'EMAIL' | 'SMS' | 'IN_APP' | 'PUSH'>;
  frequency: 'IMMEDIATE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  active: boolean;
  lastTriggered?: string;
  triggerCount: number;
  createdAt: string;
  updatedAt: string;
}

interface NotificationHistory {
  id: string;
  ruleId: string;
  ruleName: string;
  type: string;
  recipient: string;
  channel: string;
  subject: string;
  message: string;
  status: 'SENT' | 'DELIVERED' | 'FAILED' | 'PENDING';
  sentAt: string;
  deliveredAt?: string;
  failureReason?: string;
  metadata?: any;
}

interface AlertSummary {
  totalAlerts: number;
  activeAlerts: number;
  criticalAlerts: number;
  overduePayments: number;
  budgetExceeded: number;
  lowCashFlow: boolean;
  alertsByType: Array<{
    type: string;
    count: number;
    percentage: number;
  }>;
  recentAlerts: Alert[];
}

export function AlertsNotifications() {
  const [activeTab, setActiveTab] = useState('alerts');
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [notificationRules, setNotificationRules] = useState<NotificationRule[]>([]);
  const [notificationHistory, setNotificationHistory] = useState<NotificationHistory[]>([]);
  const [alertSummary, setAlertSummary] = useState<AlertSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filters, setFilters] = useState({
    type: '',
    severity: '',
    status: '',
    dateRange: 'week'
  });
  const [showCreateRuleDialog, setShowCreateRuleDialog] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  useEffect(() => {
    fetchAlertData();
  }, [filters]);

  const fetchAlertData = async () => {
    try {
      setLoading(true);
      const [alertsRes, rulesRes, historyRes, summaryRes] = await Promise.all([
        fetch(`/api/bursar/alerts?${new URLSearchParams(filters)}`),
        fetch('/api/bursar/notifications/rules'),
        fetch('/api/bursar/notifications/history'),
        fetch('/api/bursar/alerts/summary')
      ]);

      const [alertsData, rulesData, historyData, summaryData] = await Promise.all([
        alertsRes.json(),
        rulesRes.json(),
        historyRes.json(),
        summaryRes.json()
      ]);

      setAlerts(alertsData);
      setNotificationRules(rulesData);
      setNotificationHistory(historyData);
      setAlertSummary(summaryData);
    } catch (error) {
      console.error('Error fetching alert data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleAcknowledgeAlert = async (alertId: string) => {
    try {
      const response = await fetch(`/api/bursar/alerts/${alertId}/acknowledge`, {
        method: 'PATCH'
      });

      if (response.ok) {
        fetchAlertData();
      }
    } catch (error) {
      console.error('Error acknowledging alert:', error);
    }
  };

  const handleResolveAlert = async (alertId: string, resolution?: string) => {
    try {
      const response = await fetch(`/api/bursar/alerts/${alertId}/resolve`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resolution })
      });

      if (response.ok) {
        fetchAlertData();
      }
    } catch (error) {
      console.error('Error resolving alert:', error);
    }
  };

  const handleCreateNotificationRule = async (ruleData: Partial<NotificationRule>) => {
    try {
      const response = await fetch('/api/bursar/notifications/rules', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(ruleData)
      });

      if (response.ok) {
        fetchAlertData();
        setShowCreateRuleDialog(false);
      }
    } catch (error) {
      console.error('Error creating notification rule:', error);
    }
  };

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'CRITICAL': return <AlertTriangle className="h-4 w-4 text-[var(--chart-red)]" />;
      case 'HIGH': return <AlertTriangle className="h-4 w-4 text-[var(--chart-yellow)]" />;
      case 'MEDIUM': return <Clock className="h-4 w-4 text-[var(--chart-yellow)]" />;
      case 'LOW': return <Bell className="h-4 w-4 text-[var(--chart-blue)]" />;
      default: return <Bell className="h-4 w-4 text-[var(--text-secondary)]" />;
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'CRITICAL': return 'bg-[var(--danger-light)] text-[var(--danger-dark)] border-[var(--danger-light)]';
      case 'HIGH': return 'bg-[var(--warning-light)] text-[var(--warning-dark)] border-[var(--warning-light)]';
      case 'MEDIUM': return 'bg-[var(--warning-light)] text-[var(--warning-dark)] border-[var(--warning-light)]';
      case 'LOW': return 'bg-[var(--info-light)] text-[var(--info-dark)] border-[var(--info-light)]';
      default: return 'bg-[var(--bg-surface)] text-[var(--text-primary)] border-[var(--border-default)]';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'FEE_OVERDUE': return <DollarSign className="h-4 w-4" />;
      case 'LOW_CASH_FLOW': return <TrendingDown className="h-4 w-4" />;
      case 'BUDGET_EXCEEDED': return <AlertTriangle className="h-4 w-4" />;
      case 'PAYMENT_FAILED': return <DollarSign className="h-4 w-4" />;
      case 'COLLECTION_TARGET': return <Users className="h-4 w-4" />;
      default: return <Bell className="h-4 w-4" />;
    }
  };

  const alertColumns = [
    {
      header: 'Alert',
      accessorKey: 'title',
      cell: ({ row }: any) => (
        <div className="flex items-start space-x-3">
          <div className={`p-2 rounded-full ${getSeverityColor(row.original.severity)}`}>
            {getSeverityIcon(row.original.severity)}
          </div>
          <div>
            <p className="font-medium">{row.original.title}</p>
            <p className="text-sm text-[var(--text-secondary)]">{row.original.message}</p>
            {row.original.studentName && (
              <p className="text-xs text-[var(--text-muted)]">Student: {row.original.studentName}</p>
            )}
          </div>
        </div>
      )
    },
    {
      header: 'Type',
      accessorKey: 'type',
      cell: ({ row }: any) => (
        <div className="flex items-center space-x-2">
          {getTypeIcon(row.original.type)}
          <Badge variant="outline">{row.original.type.replace('_', ' ')}</Badge>
        </div>
      )
    },
    {
      header: 'Severity',
      accessorKey: 'severity',
      cell: ({ row }: any) => (
        <Badge className={getSeverityColor(row.original.severity)}>
          {row.original.severity}
        </Badge>
      )
    },
    {
      header: 'Amount',
      accessorKey: 'amount',
      cell: ({ row }: any) => (
        <span className="font-medium">
          {row.original.amount ? `KES ${row.original.amount.toLocaleString()}` : '-'}
        </span>
      )
    },
    {
      header: 'Created',
      accessorKey: 'createdAt',
      cell: ({ row }: any) => (
        <span className="text-sm">
          {new Date(row.original.createdAt).toLocaleDateString()}
        </span>
      )
    },
    {
      header: 'Status',
      accessorKey: 'status',
      cell: ({ row }: any) => (
        <Badge 
          variant={row.original.status === 'RESOLVED' ? 'default' : 'secondary'}
          className={
            row.original.status === 'RESOLVED' ? 'bg-[var(--success-light)] text-[var(--success-dark)]' :
            row.original.status === 'ACKNOWLEDGED' ? 'bg-[var(--info-light)] text-[var(--info-dark)]' :
            row.original.status === 'DISMISSED' ? 'bg-[var(--bg-surface)] text-[var(--text-primary)]' : ''
          }
        >
          {row.original.status}
        </Badge>
      )
    },
    {
      header: 'Actions',
      cell: ({ row }: any) => (
        <div className="flex space-x-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setSelectedAlert(row.original)}
          >
            <Eye className="h-4 w-4" />
          </Button>
          {row.original.status === 'ACTIVE' && (
            <>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleAcknowledgeAlert(row.original.id)}
                className="text-[var(--chart-blue)] hover:text-[var(--info-dark)]"
              >
                <CheckCircle className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleResolveAlert(row.original.id)}
                className="text-[var(--chart-green)] hover:text-[var(--success-dark)]"
              >
                Resolve
              </Button>
            </>
          )}
        </div>
      )
    }
  ];

  const ruleColumns = [
    {
      header: 'Rule',
      accessorKey: 'name',
      cell: ({ row }: any) => (
        <div>
          <p className="font-medium">{row.original.name}</p>
          <p className="text-sm text-[var(--text-muted)]">{row.original.description}</p>
        </div>
      )
    },
    {
      header: 'Trigger',
      accessorKey: 'triggerType',
      cell: ({ row }: any) => (
        <Badge variant="outline">{row.original.triggerType.replace('_', ' ')}</Badge>
      )
    },
    {
      header: 'Recipients',
      accessorKey: 'recipients',
      cell: ({ row }: any) => (
        <div className="text-sm">
          <p>{row.original.recipients.length} recipients</p>
          <div className="flex space-x-1 mt-1">
            {row.original.channels.map((channel: string) => (
              <Badge key={channel} variant="secondary" className="text-xs">
                {channel === 'EMAIL' && <Mail className="h-3 w-3 mr-1" />}
                {channel === 'SMS' && <Smartphone className="h-3 w-3 mr-1" />}
                {channel === 'IN_APP' && <Bell className="h-3 w-3 mr-1" />}
                {channel}
              </Badge>
            ))}
          </div>
        </div>
      )
    },
    {
      header: 'Frequency',
      accessorKey: 'frequency',
      cell: ({ row }: any) => (
        <Badge variant="secondary">{row.original.frequency}</Badge>
      )
    },
    {
      header: 'Triggered',
      accessorKey: 'triggerCount',
      cell: ({ row }: any) => (
        <div className="text-sm">
          <p className="font-medium">{row.original.triggerCount} times</p>
          {row.original.lastTriggered && (
            <p className="text-[var(--text-muted)]">
              Last: {new Date(row.original.lastTriggered).toLocaleDateString()}
            </p>
          )}
        </div>
      )
    },
    {
      header: 'Status',
      accessorKey: 'active',
      cell: ({ row }: any) => (
        <Badge 
          variant={row.original.active ? 'default' : 'secondary'}
          className={row.original.active ? 'bg-[var(--success-light)] text-[var(--success-dark)]' : ''}
        >
          {row.original.active ? 'Active' : 'Inactive'}
        </Badge>
      )
    }
  ];

  const historyColumns = [
    {
      header: 'Notification',
      accessorKey: 'subject',
      cell: ({ row }: any) => (
        <div>
          <p className="font-medium">{row.original.subject}</p>
          <p className="text-sm text-[var(--text-muted)]">{row.original.ruleName}</p>
        </div>
      )
    },
    {
      header: 'Recipient',
      accessorKey: 'recipient',
      cell: ({ row }: any) => (
        <span className="text-sm">{row.original.recipient}</span>
      )
    },
    {
      header: 'Channel',
      accessorKey: 'channel',
      cell: ({ row }: any) => (
        <div className="flex items-center space-x-2">
          {row.original.channel === 'EMAIL' && <Mail className="h-4 w-4" />}
          {row.original.channel === 'SMS' && <Smartphone className="h-4 w-4" />}
          {row.original.channel === 'IN_APP' && <Bell className="h-4 w-4" />}
          <Badge variant="outline">{row.original.channel}</Badge>
        </div>
      )
    },
    {
      header: 'Sent',
      accessorKey: 'sentAt',
      cell: ({ row }: any) => (
        <span className="text-sm">
          {new Date(row.original.sentAt).toLocaleDateString()}
        </span>
      )
    },
    {
      header: 'Status',
      accessorKey: 'status',
      cell: ({ row }: any) => (
        <Badge 
          variant={row.original.status === 'DELIVERED' ? 'default' : 'secondary'}
          className={
            row.original.status === 'DELIVERED' ? 'bg-[var(--success-light)] text-[var(--success-dark)]' :
            row.original.status === 'FAILED' ? 'bg-[var(--danger-light)] text-[var(--danger-dark)]' :
            row.original.status === 'PENDING' ? 'bg-[var(--warning-light)] text-[var(--warning-dark)]' : ''
          }
        >
          {row.original.status}
        </Badge>
      )
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-semibold">Alerts & Notifications</h2>
        <div className="flex space-x-2">
          <Button variant="outline">
            <Settings className="h-4 w-4 mr-2" />
            Configure Alerts
          </Button>
          <Button onClick={() => setShowCreateRuleDialog(true)}>
            <Plus className="h-4 w-4 mr-2" />
            Create Rule
          </Button>
        </div>
      </div>

      {/* Alert Summary Cards */}
      {alertSummary && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card className="p-4">
            <div className="flex items-center space-x-3">
              <Bell className="h-8 w-8 text-[var(--chart-blue)]" />
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Total Alerts</p>
                <p className="text-2xl font-bold">{alertSummary.totalAlerts}</p>
              </div>
            </div>
          </Card>
          
          <Card className="p-4">
            <div className="flex items-center space-x-3">
              <AlertTriangle className="h-8 w-8 text-[var(--chart-yellow)]" />
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Active Alerts</p>
                <p className="text-2xl font-bold">{alertSummary.activeAlerts}</p>
              </div>
            </div>
          </Card>
          
          <Card className="p-4">
            <div className="flex items-center space-x-3">
              <AlertTriangle className="h-8 w-8 text-[var(--chart-red)]" />
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Critical Alerts</p>
                <p className="text-2xl font-bold">{alertSummary.criticalAlerts}</p>
              </div>
            </div>
          </Card>
          
          <Card className="p-4">
            <div className="flex items-center space-x-3">
              <DollarSign className="h-8 w-8 text-[var(--chart-green)]" />
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Overdue Payments</p>
                <p className="text-2xl font-bold">{alertSummary.overduePayments}</p>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* Critical Alerts Banner */}
      {alertSummary && alertSummary.criticalAlerts > 0 && (
        <Card className="p-4 border-[var(--danger-light)] bg-[var(--danger-light)]">
          <div className="flex items-center space-x-2 mb-3">
            <AlertTriangle className="h-5 w-5 text-[var(--chart-red)]" />
            <h3 className="font-semibold text-[var(--danger-dark)]">Critical Alerts Require Attention</h3>
          </div>
          <div className="space-y-2">
            {alertSummary.recentAlerts
              .filter(alert => alert.severity === 'CRITICAL' && alert.status === 'ACTIVE')
              .slice(0, 3)
              .map((alert) => (
                <div key={alert.id} className="flex items-center justify-between p-2 bg-[var(--bg-main)] rounded">
                  <div>
                    <p className="text-sm font-medium">{alert.title}</p>
                    <p className="text-xs text-[var(--text-secondary)]">{alert.message}</p>
                  </div>
                  <div className="flex space-x-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleAcknowledgeAlert(alert.id)}
                    >
                      Acknowledge
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleResolveAlert(alert.id)}
                    >
                      Resolve
                    </Button>
                  </div>
                </div>
              ))}
          </div>
        </Card>
      )}

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="alerts">Active Alerts</TabsTrigger>
          <TabsTrigger value="rules">Notification Rules</TabsTrigger>
          <TabsTrigger value="history">Notification History</TabsTrigger>
          <TabsTrigger value="analytics">Alert Analytics</TabsTrigger>
        </TabsList>

        <TabsContent value="alerts" className="space-y-4">
          <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold">Alert Management</h3>
              <div className="flex space-x-4">
                <SearchInput
                  placeholder="Search alerts..."
                  value={searchTerm}
                  onChange={setSearchTerm}
                />
                <MultiFilter
                  filters={[
                    { key: 'type', label: 'Type', options: ['FEE_OVERDUE', 'LOW_CASH_FLOW', 'BUDGET_EXCEEDED', 'PAYMENT_FAILED'] },
                    { key: 'severity', label: 'Severity', options: ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] },
                    { key: 'status', label: 'Status', options: ['ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED'] }
                  ]}
                  values={filters}
                  onChange={setFilters}
                />
              </div>
            </div>
            <DataTable
              columns={alertColumns}
              data={alerts}
              loading={loading}
            />
          </Card>
        </TabsContent>

        <TabsContent value="rules" className="space-y-4">
          <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold">Notification Rules</h3>
              <Button onClick={() => setShowCreateRuleDialog(true)}>
                <Plus className="h-4 w-4 mr-2" />
                Create Rule
              </Button>
            </div>
            <DataTable
              columns={ruleColumns}
              data={notificationRules}
              loading={loading}
            />
          </Card>
        </TabsContent>

        <TabsContent value="history" className="space-y-4">
          <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold">Notification History</h3>
              <div className="flex space-x-2">
                <Button variant="outline">
                  <Send className="h-4 w-4 mr-2" />
                  Send Test Notification
                </Button>
              </div>
            </div>
            <DataTable
              columns={historyColumns}
              data={notificationHistory}
              loading={loading}
            />
          </Card>
        </TabsContent>

        <TabsContent value="analytics" className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="p-6">
              <h3 className="text-lg font-semibold mb-4">Alert Distribution by Type</h3>
              {alertSummary && (
                <div className="space-y-3">
                  {alertSummary.alertsByType.map((type) => (
                    <div key={type.type} className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        {getTypeIcon(type.type)}
                        <span className="font-medium">{type.type.replace('_', ' ')}</span>
                      </div>
                      <div className="text-right">
                        <p className="font-medium">{type.count}</p>
                        <p className="text-sm text-[var(--text-muted)]">{type.percentage}%</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            <Card className="p-6">
              <h3 className="text-lg font-semibold mb-4">Recent Alert Activity</h3>
              {alertSummary && (
                <div className="space-y-3">
                  {alertSummary.recentAlerts.slice(0, 5).map((alert) => (
                    <div key={alert.id} className="flex items-center justify-between p-3 bg-[var(--bg-surface)] rounded-lg">
                      <div className="flex items-center space-x-3">
                        <div className={`p-1 rounded-full ${getSeverityColor(alert.severity)}`}>
                          {getSeverityIcon(alert.severity)}
                        </div>
                        <div>
                          <p className="font-medium text-sm">{alert.title}</p>
                          <p className="text-xs text-[var(--text-secondary)]">
                            {new Date(alert.createdAt).toLocaleDateString()}
                          </p>
                        </div>
                      </div>
                      <Badge className={getSeverityColor(alert.severity)}>
                        {alert.severity}
                      </Badge>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}