/**
 * Admin API Route for Generating Teacher SMS Permission Codes
 * POST /api/admin/sms-permission/generate
 * Requirements: Only admins can generate permission codes that expire every 5 hours
 */

import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/db'
import { teacherSMSPermissionService } from '@/services/teacher-sms-permission.service'

interface GenerateCodeRequest {
  teacherId?: string // Optional: assign code to specific teacher
  expiresInHours?: number // Optional: custom expiration (default: 5 hours)
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }
    
    const userId = (session.user as { id?: string }).id
    const schoolId = (session.user as { schoolId?: string }).schoolId
    
    if (!userId || !schoolId) {
      return NextResponse.json(
        { error: 'Invalid session' },
        { status: 400 }
      )
    }
    
    // Verify user is admin
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { role: true }
    })
    
    if (!user || user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Only administrators can generate permission codes' },
        { status: 403 }
      )
    }
    
    const body: GenerateCodeRequest = await request.json()
    const { teacherId, expiresInHours = 5 } = body
    
    // Validate teacher exists if specified
    if (teacherId) {
      const teacher = await prisma.teacher.findUnique({
        where: {
          id: teacherId,
          schoolId,
        },
        select: { id: true, firstName: true, lastName: true }
      })
      
      if (!teacher) {
        return NextResponse.json(
          { error: 'Teacher not found' },
          { status: 404 }
        )
      }
    }
    
    // Generate the permission code
    const permissionCode = await teacherSMSPermissionService.generateCode({
      schoolId,
      adminId: userId,
      teacherId,
      expiresInHours,
    })
    
    return NextResponse.json({
      success: true,
      code: permissionCode.code,
      id: permissionCode.id,
      expiresAt: permissionCode.expiresAt,
      assignedTo: teacherId ? 'specific teacher' : 'any teacher',
      expiresInHours,
      message: `Permission code generated successfully. Expires in ${expiresInHours} hours.`
    })
    
  } catch (error) {
    console.error('Error generating permission code:', error)
    return NextResponse.json(
      { error: 'Failed to generate permission code' },
      { status: 500 }
    )
  }
}

/**
 * GET /api/admin/sms-permission/codes
 * Get all active permission codes for the school
 */
export async function GET(request: NextRequest) {
  try {
    const session = await auth()
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }
    
    const userId = (session.user as { id?: string }).id
    const schoolId = (session.user as { schoolId?: string }).schoolId
    
    if (!userId || !schoolId) {
      return NextResponse.json(
        { error: 'Invalid session' },
        { status: 400 }
      )
    }
    
    // Verify user is admin
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { role: true }
    })
    
    if (!user || user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Only administrators can view permission codes' },
        { status: 403 }
      )
    }
    
    // Get active codes
    const activeCodes = await teacherSMSPermissionService.getActiveCodes(schoolId)
    
    // Get recent codes generated by this admin
    const adminCodes = await teacherSMSPermissionService.getCodesByAdmin(userId, schoolId)
    
    return NextResponse.json({
      success: true,
      activeCodes,
      adminCodes,
      totalActive: activeCodes.length,
    })
    
  } catch (error) {
    console.error('Error fetching permission codes:', error)
    return NextResponse.json(
      { error: 'Failed to fetch permission codes' },
      { status: 500 }
    )
  }
}